spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/roommanagement;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;NON_KEYWORDS=END
    driver-class-name: org.h2.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
server:
  port: 8080
  error:
    include-message: always
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
  file:
    name: logs/roommgmt.log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    beans:
      enabled: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
