spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/roommanagement;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;NON_KEYWORDS=END
    driver-class-name: org.h2.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true

server:
  port: 8080
  error:
    include-message: always

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
  file:
    name: logs/roommgmt.log

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
  info:
    title: Room Management API
    version: 1.0.0
    description: API for managing rooms
