-- Buildings
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES ( -1, '110', 'Headquarter', true );
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES ( -2, '115', 'Data Center', false );
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES ( -3, '105', 'Canteen', true );

-- Rooms
INSERT INTO ROOM (ID, PROJECTOR_PRESENT, ROOM_NUMBER, SEATS, BUILDING_ID) VALUES ( -1, true, '0.10', 8, -1 );
INSERT INTO ROOM (ID, PROJECTOR_PRESENT, ROOM_NUMBER, SEATS, BUILDING_ID) VALUES ( -2, false, '1.22', 4, -1 );
INSERT INTO ROOM (ID, PROJECTOR_PRESENT, ROOM_NUMBER, SEATS, BUILDING_ID) VALUES ( -3, true, '3.05', 20, -1 );
INSERT INTO ROOM (ID, PROJECTOR_PRESENT, ROOM_NUMBER, SEATS, BUILDING_ID) VALUES ( -4, true, 'E.05', 8, -2 );
INSERT INTO ROOM (ID, PROJECTOR_PRESENT, ROOM_NUMBER, SEATS, BUILDING_ID) VALUES ( -5, true, 'New York', 20, -3 );
INSERT INTO ROOM (ID, PROJECTOR_PRESENT, ROOM_NUMBER, SEATS, BUILDING_ID) VALUES ( -6, false, 'Alaska', 8, -3 );
INSERT INTO ROOM (ID, PROJECTOR_PRESENT, ROOM_NUMBER, SEATS, BUILDING_ID) VALUES ( -7, true, 'Peking', 50, -3 );

-- Meetings
INSERT INTO MEETING (ID, START, END, TOPIC, ROOM_ID) VALUES ( -1, '2021-06-03 10:00:00', '2021-06-03 12:00:00', 'Sprint Planning', -3 );
