package com.spring.roommgmt.enums;

/*
 * Banners are generated by springhow.com banner generator
 */
public enum ApplicationBanner {

    ROOMMGMT("  ____                                                                                     _   \n" +
            " |  _ \\ ___   ___  _ __ ___    _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ ___   ___ _ __ | |_ \n" +
            " | |_) / _ \\ / _ \\| '_ ` _ \\  | '_ ` _ \\ / _` | '_ \\ / _` |/ _` |/ _ \\ '_ ` _ \\ / _ \\ '_ \\| __|\n" +
            " |  _ < (_) | (_) | | | | | | | | | | | | (_| | | | | (_| | (_| |  __/ | | | | |  __/ | | | |_ \n" +
            " |_| \\_\\___/ \\___/|_| |_| |_| |_| |_| |_|\\__,_|_| |_|\\__,_|\\__, |\\___|_| |_| |_|\\___|_| |_|\\__|\n" +
            "                                                           |___/                              ");

    private final String bannerText;

    ApplicationBanner(String bannerText) {
        this.bannerText = bannerText;
    }

    /**
     * Getter for the banner text
     *
     * @return bannerText
     */
    public String getBannerText() {
        return bannerText;
    }
}
